<a href="https://colab.research.google.com/github/Sampada2002/machine-learning-with-python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [186]:
import numpy as np

In [187]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [188]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [189]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [190]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [191]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [192]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [193]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [194]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [195]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [196]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [197]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [198]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [199]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [200]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [202]:
np.random.rand(3,2)

array([[0.12263037, 0.02690986],
       [0.61313901, 0.67053144],
       [0.90140939, 0.90304876]])

In [203]:
np.random.randn(3,2)

array([[-0.45284998, -0.84244251],
       [-0.06893345, -2.10168837],
       [-1.3250629 , -0.31020123]])

In [204]:
np.random.randint(34,100)

40

In [205]:
np.random.randint(1,5,2)

array([3, 4])

In [206]:
s=np.arange(30)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [207]:
rand_array=np.random.randint(0,100,20)
rand_array

array([75,  7, 24, 52, 26,  9, 45, 55, 35, 74, 51, 24, 33, 86, 81, 47, 79,
       35, 98, 40])

In [208]:
s.reshape

<function ndarray.reshape>

In [209]:
# rand_array.reshape(3,10)
# rand_array

In [210]:
rand_array.min()
rand_array

array([75,  7, 24, 52, 26,  9, 45, 55, 35, 74, 51, 24, 33, 86, 81, 47, 79,
       35, 98, 40])

In [211]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [212]:
a.T
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [213]:
a=np.random.rand(2,3)
a

array([[0.80914049, 0.8088319 , 0.17042173],
       [0.62520468, 0.51308773, 0.96216251]])

In [214]:
a.T

array([[0.80914049, 0.62520468],
       [0.8088319 , 0.51308773],
       [0.17042173, 0.96216251]])

In [215]:
s=np.arange(10,21)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [216]:
s[3]

13

In [217]:
s[3:7]

array([13, 14, 15, 16])

In [218]:
s[1:4]=100
s


array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [219]:
s=np.arange(10,21)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [220]:
s[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [221]:
subset_sample_array=s[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [222]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [223]:
subset_sample_array[:]=1002
subset_sample_array

array([1002, 1002, 1002, 1002, 1002, 1002, 1002])

In [224]:
#two dimensionqal array


In [230]:
import numpy as np

In [232]:
sample_matrix=np.array([[1,2,3],[4,5,6],[22,33,44]])
sample_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 33, 44]])

In [234]:
sample_matrix[2]
sample_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 33, 44]])

In [236]:
sample_matrix[0:2,2]

array([3, 6])

In [237]:
sample_matrix[2,:]

array([22, 33, 44])

In [240]:
sample_matrix[:,(1,2)]

array([[ 2,  3],
       [ 5,  6],
       [33, 44]])

In [242]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [243]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [244]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [245]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [246]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [247]:
np.max(sample_array)

19

In [248]:
np.min(sample_array)

1

In [249]:
np.argmax(sample_array)

18

In [250]:
np.argmin(sample_array)

0

In [251]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [252]:
np.std(sample_array)

5.477225575051661

In [253]:
np.var(sample_array)

30.0

In [254]:
np.mean(sample_array)

10.0

In [255]:
array=np.random.randn(3,4)
array

array([[-0.49232142,  0.17112492,  0.31018543, -2.02179267],
       [-1.61042726,  2.59516544,  0.02640016,  0.28568523],
       [ 0.71309301,  0.84787328, -0.86527458,  0.25834004]])

In [256]:
np.round(array,decimals=3)

array([[-0.492,  0.171,  0.31 , -2.022],
       [-1.61 ,  2.595,  0.026,  0.286],
       [ 0.713,  0.848, -0.865,  0.258]])

In [257]:
sports=np.array(['golf','football','cricket','football','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'football', 'golf'], dtype='<U10')